### PR TITLE
Refactor for new upstream library

### LINKED ISSUE #12: Connections Status not updating
Nice work.

Just found out that Connections Status will not update automatically upon device availability.
Screen Shot 2022-04-28 at 11 15 48 am

**Reproduce:** 
1. Restart companion while the Smart Plug is removed from the wall socket.
2. Connections status says "connecting".
3. Plug the Smart Plug back in and confirm the plug is online in Kasa App.
4. Connections status stays "connecting" but plug can be controlled via companion but feedback messages are not working.

All my other modules will automatically go into OK status upon network availability (when the device is up).

But if you edit and Save the connection it will become "OK" in status and feedback starts working.

### PR DESCRIPTION
**Pull request by istnv**
Should fix #12 #13 #18

### CODE REVIEW

**Comment by josephdadams** [comment]
Good job!

**Comment by scotttroyer** [comment]
I'm still experiencing [#18](https://github.com/bitfocus/companion-module-tplink-kasasmartplug/issues/18) on [3.2.2 (3.2.2+6688-stable-7417d2a0)](https://bitfocus.io/companion/)

**Comment by istnv** [comment]
@scotttroyer Stable does not have all of the recent updates.

**Comment by scotttroyer** [comment]
Thank you @istnv

**Pull request merged**
